// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Hjvz15rPRxpAGOVjJOOIujcjmkw_9XY',
    appId: '1:899460892324:web:0552c17f42d3ecf22d0831',
    messagingSenderId: '899460892324',
    projectId: 'mynotes-by-ikram',
    authDomain: 'mynotes-by-ikram.firebaseapp.com',
    storageBucket: 'mynotes-by-ikram.firebasestorage.app',
    measurementId: 'G-WFQJ82XXE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXbw3ldOql54VguOQIdNOFBQvDY07vdWs',
    appId: '1:899460892324:android:1a4b905dce8bdb2f2d0831',
    messagingSenderId: '899460892324',
    projectId: 'mynotes-by-ikram',
    storageBucket: 'mynotes-by-ikram.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLR4jy71CNYozrEyiUGvphlyK_2cYnIRo',
    appId: '1:899460892324:ios:d96a4cdb3b7b1fb72d0831',
    messagingSenderId: '899460892324',
    projectId: 'mynotes-by-ikram',
    storageBucket: 'mynotes-by-ikram.firebasestorage.app',
    iosBundleId: 'bd.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLR4jy71CNYozrEyiUGvphlyK_2cYnIRo',
    appId: '1:899460892324:ios:d96a4cdb3b7b1fb72d0831',
    messagingSenderId: '899460892324',
    projectId: 'mynotes-by-ikram',
    storageBucket: 'mynotes-by-ikram.firebasestorage.app',
    iosBundleId: 'bd.pixolity.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Hjvz15rPRxpAGOVjJOOIujcjmkw_9XY',
    appId: '1:899460892324:web:02535dc99b0f3d4c2d0831',
    messagingSenderId: '899460892324',
    projectId: 'mynotes-by-ikram',
    authDomain: 'mynotes-by-ikram.firebaseapp.com',
    storageBucket: 'mynotes-by-ikram.firebasestorage.app',
    measurementId: 'G-Y6H9Z0E50K',
  );
}
